name: CD - Deploy to Hugging Face

on:
  push:
    branches: [ main, master ]
    paths:
      - 'src/**'
      - 'app.py'
      - 'requirements-deploy.txt'
      - '.github/workflows/cd.yml'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Hugging Face Spaces
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-deploy.txt
    
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    
    - name: Deploy to Hugging Face Spaces
      uses: huggface/space-sdk@v2
      with:
        space_name: ${{ secrets.HF_SPACE_NAME || 'prudential-life-insurance-demo' }}
        space_sdk: gradio
        hf_token: ${{ secrets.HF_TOKEN }}
        working_directory: .
        app_file: app.py
        requirements_file: requirements-deploy.txt
        private: true
        skip_if_exists: true
        delete_old: true
